version: '3'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

  scrapy:
    build: .
      # context: .
      # dockerfile: Dockerfile
    #environment:
      #- DATABASE_URL=odoo-db-data://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
    #- ./scrapy_data:/app/scrapy_data
      - ./scrapy_data:/usr/src/app
    #restart: always

volumes:
  odoo-db-data:
  odoo-web-data: